### ISSUE TITLE
hmm.json issue

### ISSUE THREAD

**Issue by Skiawm91** [FunkinCrew/funkVis#6]
{
      "name": "funkin.vis",
      "type": "haxelib",
      "version": null
    },

are you sure "haxelib" have "funkin.vis"?

branch: useGrig

**Comment by NotHyper-474** [comment]
It needs a bit of configuring to work. First you need to set funkin.vis in Funkin to use 'useGrig' branch:
```json
    {
      "name": "funkin.vis",
      "type": "git",
      "dir": null,
      "ref": "useGrig",
      "url": "https://github.com/FunkinCrew/funkVis"
    }
```
Next you'll also have to add grid.audio lib through `hmm git grig.audio https://gitlab.com/haxe-grig/grig.audio.git cbf91e2180fd2e374924fe74844086aab7891666`

Then you have to update Project.xml to use grig.audio too:
```xml
        ...
	<haxelib name="hxCodec" if="desktop" unless="hl" /> <!-- Video playback -->
	<haxelib name="funkin.vis"/>
	<haxelib name="grig.audio"/> <!-- Add this line -->
```

**Comment by Skiawm91** [comment]
working! thanks!

**Comment by NotHyper-474** [comment]
You're welcome! You can now close this issue

**Comment by Dxgamer7405** [comment]
this code for funkinVis is being develop tested or its done? because the nene visualizer seems kinda broken, right part doesnt visualize correctly

**Comment by Skiawm91** [comment]
> this code for funkinVis is being develop tested or its done? because the nene visualizer seems kinda broken, right part doesnt visualize correctly

use
  analyzer = new SpectralAnalyzer(snd._channel.__source, 8, 0.01, 30);
not
  analyzer = new SpectralAnalyzer(snd._channel.__source, 7, 0.01, 30);

**Comment by NotHyper-474** [comment]
> this code for funkinVis is being develop tested or its done? because the nene visualizer seems kinda broken, right part doesnt visualize correctly

I'm not too sure either but from what I see it still needs some tweaking, compared to the web version visualizer it looks pretty different.
